### ISSUE TITLE
where to find XTRACT.m script?

### ISSUE THREAD

**Issue by Agajan241b** [fengqzHD/gmIdNeoKit#8]
where can I find the script XTRACT.m?
every time I use the function, I get "Undefined variable "XTRACT" or class "XTRACT.m" "

**Comment by fengqzHD** [comment]
Could you show me more background of this question? Which script are you running and where do you get this error?

**Comment by Agajan241b** [comment]
> Could you show me more background of this question? Which script are you running and where do you get this error?

Thank you for quick reply. I am using to replicate an example from the book Systematic Design of Analog CMOS Circuits:

y = XTRACT(nch,L,VDsat,0);

**Comment by chip360** [comment]
PS E:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI> python -u "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py"
Load Mat File : 180msrf_nch_tt_full.mat
Loading complete!
VGS : from 0.000 to 1.800 with step of 0.020
VDS : from 0.000 to 1.800 with step of 0.020
VSB : from 0.300 to 0.000 with step of -0.150
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 658, in MosMatSet
    self.loadMat()
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 1041, in loadMat
    self.ui.spinBoxBiasVds.setValue(1000.0*self.VDS)
TypeError: setValue(self, val: int): argument 1 has unexpected type 'numpy.float64'
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 578, in PlotRef
    self.visibleRef(True)
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 1507, in visibleRef
    self.corCurveIdDRef[self.tgtCorner].setVisible(curveState)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'setVisible'
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 701, in PlotUpdate
    self.cornerMat()
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 1049, in cornerMat
    self.tgtCorner = self.listCorner.index(self.matFileInfo[2])
                                           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 932, in SynMos
    self.synVGS, self.synState = self.SearchVGSG( self.tgtCorner, self.synGmId, self.Lchk, 4)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 968, in SearchVGSG
    gmIdSeq = lp.lookupfz(self.mosCorner[cornerIndex], self.mosModel, 'GMOVERID', VDS=self.VDS, VSB=self.VSB, L=tgtL, VGS=vgsSeq)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\LupMos.py", line 166, in lookupfz
    defaultL =  min(mosDat['L'][0])
                    ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 932, in SynMos
    self.synVGS, self.synState = self.SearchVGSG( self.tgtCorner, self.synGmId, self.Lchk, 4)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 968, in SearchVGSG
    gmIdSeq = lp.lookupfz(self.mosCorner[cornerIndex], self.mosModel, 'GMOVERID', VDS=self.VDS, VSB=self.VSB, L=tgtL, VGS=vgsSeq)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\LupMos.py", line 166, in lookupfz
    defaultL =  min(mosDat['L'][0])
                    ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 932, in SynMos
    self.synVGS, self.synState = self.SearchVGSG( self.tgtCorner, self.synGmId, self.Lchk, 4)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 968, in SearchVGSG
    gmIdSeq = lp.lookupfz(self.mosCorner[cornerIndex], self.mosModel, 'GMOVERID', VDS=self.VDS, VSB=self.VSB, L=tgtL, VGS=vgsSeq)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\LupMos.py", line 166, in lookupfz
    defaultL =  min(mosDat['L'][0])
                    ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 932, in SynMos
    self.synVGS, self.synState = self.SearchVGSG( self.tgtCorner, self.synGmId, self.Lchk, 4)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\runGmIdSizing.py", line 968, in SearchVGSG
    gmIdSeq = lp.lookupfz(self.mosCorner[cornerIndex], self.mosModel, 'GMOVERID', VDS=self.VDS, VSB=self.VSB, L=tgtL, VGS=vgsSeq)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\BaiduSyncdisk\科研小学生\实验记录\gmid的设计方法\gmIdNeoKit-master\gmIdNeoKit-master\GUI\LupMos.py", line 166, in lookupfz
    defaultL =  min(mosDat['L'][0])
                    ~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

I have a query, presently when I attempt to open a Python file, it consistently encounters errors, specifically pertaining to the inability to execute plotting and computation. Would you kindly extend your assistance to me?
